language: node_js
node_js:
- '5.1'
sudo: false
install:
- npm install
- npm install eslint
script: npm run-script test
after_success: sh publish.sh
before_install:
- openssl aes-256-cbc -K $encrypted_7563c8fbc5a5_key -iv $encrypted_7563c8fbc5a5_iv -in .npmrc.enc -out ~/.npmrc -d
