output_path: builds/prod
# git clone
before_install:
    - yarn
# download materials
# generate otsimo.json
# generate locale datas
after_install:
    - yarn run build
deploy: 
    - |
        BUILD_ENV=""
        if [ "$OTSIMO_DEPLOY_TYPE" = "staging" ];then
            BUILD_ENV="--staging"
        fi
        otsimoctl --debug ${BUILD_ENV} game publish --release --dir ./dist
before_preview:
    - echo "Preview"
